import React from "react";
import HeadNext from "next/head";

export function Head({}) {
  return (
    <HeadNext>
      <title>Bataklik Portfolio</title>
      <meta name="description" content="Generated by Bataklik" />
      <link rel="icon" href="/favicon.ico" />
    </HeadNext>
  );
}
